                                  LINEAR REGRESSION WITH SCIKIT LEARN

In [105]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler 

In [106]:
#data
x_train=np.array([[1500,4,4,2],[2100,5,4,3],[2600,5,3,6]])
y_train=np.array([250,320,400])

In [107]:
scaler=StandardScaler()
x_train01=scaler.fit_transform(x_train)

In [108]:
x_train01

array([[-1.26012384, -1.41421356,  0.70710678, -0.98058068],
       [ 0.07412493,  0.70710678,  0.70710678, -0.39223227],
       [ 1.18599891,  0.70710678, -1.41421356,  1.37281295]])

In [109]:
sgdr=SGDRegressor(max_iter=10000)
sgdr.fit(x_train01,y_train)

SGDRegressor(max_iter=10000)

In [110]:
w=sgdr.coef_
b=sgdr.intercept_

In [111]:
w=w.reshape(-1,1)

In [113]:
print(b)

array([322.84108237])

In [114]:
#Prediction
pred=np.dot(x_train01,w)+b

In [142]:
print(pred)

[[249.59035138]
 [319.36266267]
 [399.57023306]]


In [130]:
#NEW DATA
new_data=np.array([2600,5,3,6]).reshape(-1,1)

In [131]:
#Normalizing
sc=StandardScaler()
new_data01=sc.fit_transform(new_data)

In [136]:
new_data01=new_data01.reshape(-1,4)

In [140]:
preeed=sgdr.predict(new_data01)

In [144]:
print(preeed)

[343.30755208]
